services:
  plane-mq:
    image: rabbitmq:3.13-management-alpine
    container_name: pms-mq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-plane}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-plane_pass}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-plane}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - plane-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  plane-network:
    external: true
    name: plane-network
