#!/bin/bash

# Configure the platform for GitHub Codespaces access.
# Run once after `up.sh` when working inside a Codespace.
# Usage: ./scripts/setup-codespace.sh

PLATFORM_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PLATFORM_ROOT"

if [ -f .env ]; then
    set -a; source .env; set +a
fi

# ── Validate environment ──────────────────────────────────────────────
if [ -z "$CODESPACE_NAME" ] || [ -z "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    echo "❌ Not running inside GitHub Codespaces."
    echo "   This script is only needed in a Codespace environment."
    exit 1
fi

FWD_DOMAIN="$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN"
CS_APP="https://${CODESPACE_NAME}-443.${FWD_DOMAIN}"
CS_AUTH="https://${CODESPACE_NAME}-9000.${FWD_DOMAIN}"
CS_TRAEFIK="https://${CODESPACE_NAME}-8080.${FWD_DOMAIN}"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║         Codespace Environment Setup                       ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "Codespace : $CODESPACE_NAME"
echo "App URL   : $CS_APP"
echo "Authentik : $CS_AUTH"
echo "Traefik   : $CS_TRAEFIK"
echo ""

# ── Step 1: Traefik dynamic config for Codespace hostname ─────────────
echo "▶ Step 1: Configuring Traefik routes for Codespace URL..."

# Ensure the dynamic config directory is writable
sudo chmod 777 traefik/dynamic 2>/dev/null || true

CS_HOST="${CODESPACE_NAME}-443.${FWD_DOMAIN}"

cat > traefik/dynamic/codespace.yml << EOF
# Auto-generated by setup-codespace.sh — do not edit manually
# Adds path-based routing for the Codespace forwarded URL.
http:
  routers:
    cs-api:
      entryPoints: [websecure]
      rule: "Host(\`${CS_HOST}\`) && PathPrefix(\`/api\`)"
      service: cs-plane-api
      tls: {}
      priority: 20

    cs-ws:
      entryPoints: [websecure]
      rule: "Host(\`${CS_HOST}\`) && PathPrefix(\`/ws\`)"
      service: cs-plane-live
      tls: {}
      priority: 15

    cs-spaces:
      entryPoints: [websecure]
      rule: "Host(\`${CS_HOST}\`) && PathPrefix(\`/spaces\`)"
      service: cs-plane-space
      tls: {}
      priority: 10

    cs-god-mode:
      entryPoints: [websecure]
      rule: "Host(\`${CS_HOST}\`) && PathPrefix(\`/god-mode\`)"
      service: cs-plane-admin
      tls: {}
      priority: 10

    cs-frontend:
      entryPoints: [websecure]
      rule: "Host(\`${CS_HOST}\`)"
      service: cs-plane-frontend
      tls: {}
      priority: 1

  services:
    cs-plane-api:
      loadBalancer:
        servers:
          - url: "http://platform-plane-backend:8000"

    cs-plane-frontend:
      loadBalancer:
        servers:
          - url: "http://platform-plane-frontend:3000"

    cs-plane-space:
      loadBalancer:
        servers:
          - url: "http://platform-plane-space:3001"

    cs-plane-admin:
      loadBalancer:
        servers:
          - url: "http://platform-plane-admin:3002"

    cs-plane-live:
      loadBalancer:
        servers:
          - url: "http://platform-plane-live:3003"
EOF

echo "  ✅ traefik/dynamic/codespace.yml written (Traefik auto-reloads)"
sleep 2

# ── Step 2: Expose Authentik on port 9000 directly ───────────────────
echo ""
echo "▶ Step 2: Exposing Authentik on port 9000 for direct access..."

# Authentik needs its own port since it can't share path-based routing
# Check if port 9000 is already exposed
if docker port platform-authentik-server 2>/dev/null | grep -q "9000"; then
    echo "  ✅ Authentik port 9000 already exposed"
else
    # Add port binding to authentik by recreating with port
    docker compose -p "$COMPOSE_PROJECT_NAME" --env-file .env \
        -f authentik/docker-compose.yml up -d --force-recreate 2>/dev/null
    echo "  ℹ️  Authentik recreated — if port 9000 still not exposed, see note below"
fi

# ── Step 3: Recreate frontend with Codespace URLs ─────────────────────
echo ""
echo "▶ Step 3: Updating Plane CE frontend with Codespace URLs..."

# Recreate plane-frontend with Codespace-aware env vars
docker rm -f platform-plane-frontend 2>/dev/null || true

docker run -d \
    --name platform-plane-frontend \
    --network proxy \
    --restart unless-stopped \
    -e PORT=3000 \
    -e HOSTNAME=0.0.0.0 \
    -e NEXT_PUBLIC_API_BASE_URL="${CS_APP}/api" \
    -e NEXT_PUBLIC_WEB_URL="${CS_APP}" \
    -e NEXT_PUBLIC_ADMIN_BASE_URL="${CS_APP}/god-mode" \
    -e NEXT_PUBLIC_ASSET_PREFIX="${CS_APP}" \
    -l "traefik.enable=true" \
    -l "traefik.http.routers.plane-frontend.entrypoints=websecure" \
    -l "traefik.http.routers.plane-frontend.rule=Host(\`app.${DOMAIN}\`) && PathPrefix(\`/\`)" \
    -l "traefik.http.routers.plane-frontend.tls=true" \
    -l "traefik.http.routers.plane-frontend.priority=1" \
    -l "traefik.http.services.plane-frontend.loadbalancer.server.port=3000" \
    makeplane/plane-frontend:latest \
    node /app/web/server.js

echo "  ✅ plane-frontend restarted with Codespace URLs"
sleep 5

# ── Step 4: Verify Traefik picked up new routes ───────────────────────
echo ""
echo "▶ Step 4: Verifying Traefik routes..."

sleep 3
CS_ROUTES=$(curl -s http://localhost:8080/api/http/routers 2>/dev/null | python3 -c "
import sys, json
routers = json.load(sys.stdin)
cs = [r.get('name') for r in routers if r.get('name','').startswith('cs-')]
print(' '.join(cs))
" 2>/dev/null)

if [ -n "$CS_ROUTES" ]; then
    echo "  ✅ Codespace routes active: $CS_ROUTES"
else
    echo "  ⚠️  Routes not yet visible — Traefik may still be reloading (wait 5s and retry)"
fi

# ── Step 5: Test the Codespace URL ────────────────────────────────────
echo ""
echo "▶ Step 5: Testing Codespace endpoints..."

test_url() {
    local url=$1 name=$2
    code=$(curl -k -s -o /dev/null -w "%{http_code}" --max-time 10 "$url" 2>/dev/null)
    if echo "$code" | grep -qE "^(200|301|302|308|401)$"; then
        echo "  ✅ $name → HTTP $code"
    else
        echo "  ⚠️  $name → HTTP $code (may still be starting)"
    fi
}

test_url "$CS_APP/"         "Plane CE"
test_url "$CS_APP/api/instances/" "Plane CE API"

# ── Summary ───────────────────────────────────────────────────────────
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                  Access Your Services                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "  🌐 Plane CE    : $CS_APP"
echo "  🌐 Traefik     : $CS_TRAEFIK/dashboard/"
echo ""
echo "  🔑 Authentik setup:"
echo "     1. In VS Code → PORTS tab → forward port 9000"
echo "     2. Open: $CS_AUTH/if/flow/initial-setup/"
echo ""
echo "  📋 Login credentials:"
echo "     Email   : ${PLANE_ADMIN_EMAIL}"
echo "     Password: ${PLANE_ADMIN_PASSWORD}"
echo ""
echo "  ⚠️  Note: Traefik TLS uses a self-signed cert."
echo "     GitHub Codespace proxy handles its own TLS, so your"
echo "     browser should trust the *.app.github.dev cert."
echo ""
echo "  ℹ️  If PORTS tab shows 'private', click the port and"
echo "     set visibility to 'Public' to share with teammates."
